version: '3'

services:
    next-app:
        container_name: nextjs_template
        build:
            context: ./
            target: runner
            dockerfile: Dockerfile
        restart: always
        ports:
            - 3000:3000
        env_file:
            - .env.local
        environment:
            - NODE_ENV=production
        networks:
            - default